---
#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Configuration file for htmltest
# See: https://github.com/wjdp/htmltest

DirectoryPath: build/site/docs
OutputDir: .cache/htmltest
ExternalTimeout: 60 # (seconds) default is 15.

# Ignore internal URLs causing legit errors on the 404.html
IgnoreInternalURLs:
  - /che/docs/_/css/extra.css
  - /che/docs/_/css/site.css
  - /che/docs/_/font-awesome-4.7.0/css/font-awesome.min.css
  - /che/docs/_/img/icon-eclipse-che.svg
  - /che/docs/_/js/site.js
  - /che/docs/_/js/vendor/highlight.js
  - /che/docs/docs/che-7/overview/introduction-to-eclipse-che/
  - /che/docs/docs/devworkspaces/user-guide/starting-a-workspace-using-the-dashboard/
  - /che/docs/favicon.ico

# Ignore external URLs
IgnoreURLs:
  - https://cse.google.com/cse.js
  - https://github.com/eclipse/che-docs/edit/master/
  - https://marketplace.visualstudio.com
  - https://projectlombok.org/
  - https://www.eclipse.org/che/docs
